# ===============================
# BASE DE DATOS (PROD)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT CONFIGURACION
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration.web=${JWT_EXPIRATION_WEB}

# ===============================
# ADMIN INICIAL
# ===============================
admin.correo=${ADMIN_CORREO:admin@medicit.com}
admin.contrasena=${ADMIN_CONTRASENA:admin123}

# ===============================
# PACIENTE DE PRUEBA
# ===============================
paciente.correo=${PACIENTE_CORREO:test@medicit.com}
paciente.contrasena=${PACIENTE_CONTRASENA:Test@123}
