# ===============================
# BASE DE DATOS (DEV)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5433}/medicit
spring.datasource.username=postgres
spring.datasource.password=${DB_PASS:porta1258}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT CONFIGURACION
# ===============================
jwt.secret=mi_clave_super_segura_de_32_caracteres_minimo_123456
jwt.expiration.web=86400000

# ===============================
# ADMIN INICIAL
# ===============================
admin.correo=admin@medicit.com
admin.usuario=admin
admin.contrasena=admin123
